openapi: 3.0.1
info:
  title: Preclik E-Shop REST API documentation
  description: Official REST documentation
  contact:
    name: Ondřej Chrbolka
    email: ondrej.chrbolka@gmail.com
  version: 0.0.1
servers:
- url: http://localhost:8080
tags:
- name: Product v1
  description: Managing products from e-shop
- name: Order v1
  description: Ordering products from e-shop
paths:
  /v1/product/{id}:
    get:
      tags:
      - Product v1
      summary: Find product based on id
      operationId: findById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "404":
          description: Product not found
          content:
            text/plain: {}
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDtoIdV1'
        "400":
          description: Check your request
          content:
            text/plain: {}
    put:
      tags:
      - Product v1
      summary: Edit product
      operationId: edit
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDtoIdV1'
        required: true
      responses:
        "404":
          description: Product not found
          content:
            text/plain: {}
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDtoIdV1'
        "400":
          description: Check your request
          content:
            text/plain: {}
    delete:
      tags:
      - Product v1
      summary: Remove product (set its state to not available)
      operationId: remove
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "404":
          description: Product not found
          content:
            text/plain: {}
        "204":
          description: Success
          content:
            text/plain: {}
        "400":
          description: Check your request
          content:
            text/plain: {}
  /v1/product/{id}/quantity/increase/{quantity}:
    put:
      tags:
      - Product v1
      summary: Increase quantity of product
      operationId: increaseQuantity
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: quantity
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "404":
          description: Product not found
          content:
            text/plain: {}
        "204":
          description: Success
          content:
            text/plain: {}
        "400":
          description: Check your request
          content:
            text/plain: {}
  /v1/product/{id}/quantity/decrease/{count}:
    put:
      tags:
      - Product v1
      summary: Decrease quantity of product
      operationId: decreaseQuantity
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: count
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "404":
          description: Product not found
          content:
            text/plain: {}
        "204":
          description: Success
          content:
            text/plain: {}
        "400":
          description: Check your request
          content:
            text/plain: {}
  /v1/order/{orderId}/product/{productId}/quantity/increase/{count}:
    put:
      tags:
      - Order v1
      summary: Increase order product quantity
      operationId: increase
      parameters:
      - name: orderId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: productId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: count
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "204":
          description: Success
          content:
            text/plain: {}
        "404":
          description: Order not found
          content:
            text/plain: {}
        "409":
          description: Not enough quantity or product is not available on stock
          content:
            text/plain: {}
        "400":
          description: Check your request
          content:
            text/plain: {}
  /v1/order/{orderId}/product/{productId}/quantity/edit/{count}:
    put:
      tags:
      - Order v1
      summary: Edit order
      operationId: edit_1
      parameters:
      - name: orderId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: productId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: count
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "204":
          description: Success
          content:
            text/plain: {}
        "404":
          description: Order not found
          content:
            text/plain: {}
        "400":
          description: Check your request
          content:
            text/plain: {}
  /v1/order/{orderId}/product/{productId}/quantity/decrease/{count}:
    put:
      tags:
      - Order v1
      summary: Decrease order product quantity
      operationId: decrease
      parameters:
      - name: orderId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: productId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: count
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "204":
          description: Success
          content:
            text/plain: {}
        "409":
          description: Product not available
          content:
            text/plain: {}
        "404":
          description: Order not found
          content:
            text/plain: {}
        "400":
          description: Check your request
          content:
            text/plain: {}
  /v1/order/{id}/pay:
    put:
      tags:
      - Order v1
      summary: Pay order
      operationId: pay
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: Success
          content:
            text/plain: {}
        "410":
          description: Order contains product which is not available
          content:
            text/plain: {}
        "404":
          description: Order not found
          content:
            text/plain: {}
        "400":
          description: Check your request
          content:
            text/plain: {}
  /v1/product:
    get:
      tags:
      - Product v1
      summary: Find all products
      operationId: findAll
      parameters:
      - name: pageable
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Pageable'
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
    post:
      tags:
      - Product v1
      summary: Add product
      operationId: add
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDtoV1'
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDtoIdV1'
        "400":
          description: Check your request
          content:
            text/plain: {}
  /v1/order:
    post:
      tags:
      - Order v1
      summary: Create new order
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/EOrderProductIdDtoV1'
        required: true
      responses:
        "404":
          description: Products not found
          content:
            text/plain: {}
        "409":
          description: Not enough quantity of product on stock
          content:
            text/plain: {}
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EOrderDtoV1'
        "400":
          description: Check your request
          content:
            text/plain: {}
  /v1/order/{id}:
    get:
      tags:
      - Order v1
      summary: Find order based on id
      operationId: findById_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "404":
          description: Product not found
          content:
            text/plain: {}
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDtoIdV1'
        "400":
          description: Check your request
          content:
            text/plain: {}
    delete:
      tags:
      - Order v1
      summary: Disable order
      operationId: disable
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: Success
          content:
            text/plain: {}
        "404":
          description: Order not found
          content:
            text/plain: {}
        "400":
          description: Check your request
          content:
            text/plain: {}
components:
  schemas:
    PriceDtoV1:
      required:
      - amount
      - currency
      - validFrom
      type: object
      properties:
        id:
          type: integer
          format: int64
        amount:
          type: number
          format: double
        currency:
          type: string
          enum:
          - CZK
          - EUR
          - USD
        validFrom:
          type: string
          format: date-time
    ProductDtoIdV1:
      required:
      - available
      - name
      - price
      - quantity
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        available:
          type: boolean
        quantity:
          type: integer
          format: int32
        price:
          $ref: '#/components/schemas/PriceDtoV1'
    ProductDtoV1:
      required:
      - available
      - name
      - price
      - quantity
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        available:
          type: boolean
        quantity:
          type: integer
          format: int32
        price:
          $ref: '#/components/schemas/PriceDtoV1'
    EOrderProductIdDtoV1:
      required:
      - productId
      - quantity
      type: object
      properties:
        productId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
    EOrderDtoV1:
      required:
      - creationDate
      type: object
      properties:
        id:
          type: integer
          format: int64
        orderState:
          type: string
          enum:
          - OPEN
          - PAIED
          - CANCEL
          - EXPIRED
          - NOT_CREATED
        creationDate:
          type: string
          format: date-time
    Pageable:
      type: object
      properties:
        page:
          minimum: 0
          type: integer
          format: int32
        size:
          minimum: 1
          type: integer
          format: int32
        sort:
          type: array
          items:
            type: string
